title: Climate Change Impacts on Traffic around the Baltic Sea
description: IBA-Cristal
theme: minima
header_pages:
  - index.md
  - about.md
  - preciptype.md
  - precip_HCLIM.md
  - rstemp.md
  - rscond.md
  - freezethaw.md
  #- waterdepth.md
  #- snowdepth.md
