title: Climate Change & Traffic
description: Climate change impacts on traffic around the Baltic sea
theme: minima
header_pages:
  - index.md
  - precip_HCLIM.md
  - preciptype.md
  - roadweather.md
  - temprange.md
  - Wind.md
  - snowfalldays.md
  - about.md
  - references.md
  #- rstemp.md
  #- rscond.md
  #- freezethaw.md
  #- waterdepth.md
  #- snowdepth.md
