title: Climate Change & Traffic
description: Climate change impacts on traffic around the Baltic sea
theme: minima
header_pages:
  - index.md
  - about.md
  - preciptype.md
  - precip_HCLIM.md
  - Rx1day_CORDEX.md
  - R20mm_CORDEX.md
  - roadweather.md
  - anton.md 
  - data.md
  - references.md
  #- rstemp.md
  #- rscond.md
  #- freezethaw.md
  #- waterdepth.md
  #- snowdepth.md
