title: Climate knowledge for resilient transport in the Baltic Region
description: IBA-CRISTAL project of the Finnish Meteorological Institute | Funded by Ministry for Foreign Affairs of Finland
theme: minima
header_pages:
  - index.md
  - precip_HCLIM.md
  - preciptype.md
  - roadweather.md
  - maxwind.md
  - temprange.md
  - snowfalldays.md
  - seaice.md
  - about.md
  - references.md
  #- rstemp.md
  #- rscond.md
  #- freezethaw.md
  #- waterdepth.md
  #- snowdepth.md
